spring:
  datasource:
    url: jdbc:p6spy:h2:file:/Users/wjdev/jpaShop;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

logging:
  level:
    com.p6spy: DEBUG
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
